language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- nvm install stable
- npm install netlify-cli -g
